/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   multipart-form-item-behavior.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../iron-validatable-behavior/iron-validatable-behavior.d.ts" />
/// <reference path="../iron-form-element-behavior/iron-form-element-behavior.d.ts" />

declare namespace ArcBehaviors {

  /**
   * A common functions for payload form editors.
   */
  interface MultipartFormItemBehavior extends Polymer.IronFormElementBehavior, Polymer.IronValidatableBehavior {
    name: string|null|undefined;

    /**
     * A view model. May contain RAML type definition.
     */
    model: object|null|undefined;

    /**
     * True to render documentation (if set in model)
     */
    docsOpened: boolean|null|undefined;

    /**
     * Toggles documentation (if available)
     */
    toggleDocumentation(): void;
  }

  const MultipartFormItemBehavior: object;
}
