/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   multipart-file-form-item.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

import {IronValidatableBehavior} from '@polymer/iron-validatable-behavior/iron-validatable-behavior.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

import {mixinBehaviors} from '@polymer/polymer/lib/legacy/class.js';

/**
 * A file form item.
 */
declare class MultipartFileFormItem extends
  Polymer.IronValidatableBehavior(
  Object) {

  /**
   * Computed value, true if the control has a file.
   */
  readonly hasFile: boolean|null|undefined;

  /**
   * Name of this control
   */
  name: string|null|undefined;

  /**
   * Valuie of this control.
   */
  value: string|null|undefined;

  /**
   * A view model.
   */
  model: object|null|undefined;

  /**
   * True to render documentation (if set in model)
   */
  docsOpened: boolean|null|undefined;

  /**
   * Toggles documentation (if available)
   */
  toggleDocumentation(): void;
  _getValidity(): any;

  /**
   * Tests if current value is a type of `Blob`.
   *
   * @param value Value to test
   */
  _computeHasFile(value: String|Blob|File|null|undefined): Boolean|null;

  /**
   * A handler to choose file button click.
   * This function will find a proper input[type="file"] and programatically click on it to open
   * file dialog.
   */
  _selectFile(): void;

  /**
   * A handler to file change event for input[type="file"].
   * This will update files array for corresponding `this.filesList` array object.
   */
  _fileObjectChanged(e: Event|null): void;

  /**
   * Computes the `accept`attribute for file input.
   */
  _computeAccept(model: object|null): String|null;
}

declare global {

  interface HTMLElementTagNameMap {
    "multipart-file-form-item": MultipartFileFormItem;
  }
}
