/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   multipart-text-form-item.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {afterNextRender} from '@polymer/polymer/lib/utils/render-status.js';

import {IronValidatableBehavior} from '@polymer/iron-validatable-behavior/iron-validatable-behavior.js';

import {html} from '@polymer/polymer/lib/utils/html-tag.js';

import {mixinBehaviors} from '@polymer/polymer/lib/legacy/class.js';

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

/**
 * A text form item.
 *
 * If the browser has native support for FormData (and iterators) then it will also render
 * a content type selector for the input field.
 */
declare class MultipartTextFormItem {

  /**
   * Name of this control
   */
  name: string|null|undefined;

  /**
   * Valuie of this control.
   */
  value: string|null|undefined;

  /**
   * A view model.
   */
  model: object|null|undefined;

  /**
   * True to render documentation (if set in model)
   */
  docsOpened: boolean|null|undefined;

  /**
   * Reference to the mime type input
   */
  _mimeInput: HTMLElement|null|undefined;

  /**
   * A content type of the form field to be presented in the Multipart request.
   */
  type: string|null|undefined;

  /**
   * List of suggested mime types
   */
  suggestions: any[]|null|undefined;

  /**
   * If set it will also renders mime type selector for the input data.
   */
  hasFormData: boolean|null|undefined;

  /**
   * Toggles documentation (if available)
   */
  toggleDocumentation(): void;
  ready(): void;
  _getValidity(): any;
  _hasFormDataChanged(hasFormData: any): void;
  _setAutocompleteTarget(): void;
}

declare global {

  interface HTMLElementTagNameMap {
    "multipart-text-form-item": MultipartTextFormItem;
  }
}
